name = "my-tg-bot"
# 如果你的 index.js 在根目录下，请保持这一行
# 如果报错仍然提示找不到文件，请确认文件名是否真的是 index.js
main = "index.js" 
compatibility_date = "2024-11-30"

[[kv_namespaces]]
binding = "TOPIC_MAP"
id = "ce49ac174c594e4a940dfc6714b6bde8"

[vars]
SUPERGROUP_ID = "-1003809033535" # 请填入你截图中的那个 ID

[observability.logs]
enabled = true
invocation_logs = true

[observability]
enabled = false
head_sampling_rate = 1
