name = "my-tg-bot"
main = "worker.js" 
compatibility_date = "2024-11-30"

[[kv_namespaces]]
binding = "TOPIC_MAP"
id = "ce49ac174c594e4a940dfc6714b6bde8"

[vars]

[observability.logs]
enabled = true
invocation_logs = true

[observability]
enabled = false
head_sampling_rate = 1
